### ISSUE TITLE
Documentar o projeto e o README em Inglês

### ISSUE THREAD

**Issue by wesleyabreu** [wesleyabreu/mapa-sinais-operadoras#1]
Criar uma versão no idioma inglês da documentação do projeto

**Comment by gustavomarzoque** [comment]
Oi Wesley, tudo bem? Eu e meu grupo da disciplina Desenvolvimento de Software Livre da UFLA queríamos ajudar nessa Issue.

**Comment by wesleyabreu** [comment]
Ok
