### ISSUE TITLE
Traduzir o processador.py para Inglês

### ISSUE THREAD

**Issue by wesleyabreu** [wesleyabreu/mapa-sinais-operadoras#2]
Criar versão em inglês do programa (Linguagem padrão do Github)

**Comment by gustavomarzoque** [comment]
Oi Wesley, tudo bem? Eu e meu grupo da disciplina Desenvolvimento de Software Livre da UFLA queríamos ajudar nessa Issue.

**Comment by wesleyabreu** [comment]
Ok
